<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Create account form template
 *
 * @var $block \Magento\Customer\Block\Form\Register
 */
?>
<?php
$helper = $this->helper('Iksula\Carriercodetelephone\Helper\Data');
                    $Baseurl = $helper->getBaseUrl();

                    $NationlityOptions = $helper->getNationalityData();

                    foreach($NationlityOptions as $aNationlity){
                        $aNationiltyData [$aNationlity['value']] = $aNationlity['label'];
                    }

 echo $block->getChildHtml('form_fields_before')?>
<?php /* Extensions placeholder */ ?>
<?php echo $block->getChildHtml('customer.form.register.extra')?>
<form class="form create account form-create-account" action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <fieldset class="fieldset create info">
        <h3><?php /* @escapeNotVerified */ echo __('Create New Account') ?></h3>
        <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
        <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">
        <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
        <div class="field required">
            <div class="control">
                <input type="email" name="email" autocomplete="email" id="email_address" value="<?php echo $block->escapeHtml($block->getFormData()->getEmail()) ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" placeholder="Email Address">
            </div>
        </div>
        <div class="two_fields clear">
        <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
            <div class="control">
                <input type="password" name="password" id="password"
                title="<?php /* @escapeNotVerified */ echo __('Password') ?>"
                class="input-text"
                data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                data-validate="{required:true, 'validate-customer-password':true}"
                autocomplete="off" placeholder="Password">
            </div>
        </div>
        <div class="field confirmation required">
            <div class="control">
                <input type="password" name="password_confirmation" title="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off" placeholder="Confirm Password">
            </div>
        </div>
        </div>
        <!--div class="two_fields choice clear phone_wrap">
            <div class="field">
                <div class="tele_div">
                    <select class = "validate-select" id="country_code" name="country_code">
                    <option value="">Country Code</option>
                    </select>
                </div>
                <div class="tele_div">
                <select class = "validate-select" id="carrier_code" name="carrier_code">
                    <option value="">Carrier Code</option>
                </select>
                </div>
            </div>
            <div class="field">
                <input type="text" id="tele_number" name="tele_number" data-validate="{required:true , 'validate-number':true}" class="input-text mobile7digit" maxlength = "7" value="" placeholder="Contact Number (Enter 7 digits)" />
                <input type="hidden" name= "account_telephone" id="account_telephone" value="" />
            </div>
        </div-->

        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <?php echo $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
        <?php endif ?>

        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?php echo $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
        <?php endif ?>

        <?php /*$_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <?php echo $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
        <?php endif*/ ?>
        <div class="three_fields clear">
        <div class="field choice">
                <select class = "validate-select" name="nationality">
                <option value="" >Nationality</option>
                <?php foreach($aNationiltyData as $label => $Values) {?>
                        <option value="<?php echo $label; ?>"><?php echo $Values; ?></option>
                <?php }?>
                </select>
        </div>

        <div class="field">
            <div class="gender_wrap clear">
            <div class="gender_div"><input type="radio" name="gender" checked="checked" id="male" class="checkbox" value = "1">
              <label class="label" for="male">Male</label></div>
            <div class="gender_div"><input type="radio" name="gender" id="female" class="checkbox" value = "2" >
              <label class="label" for="female">Female</label></div>
            </div>
        </div>

        <div class="field">
            <div class="choice newsletter">
            <input type="checkbox" name="is_subscribed" title="<?php /* @escapeNotVerified */ echo __('Subscribe 2XL Newsletter') ?>" value="1" id="is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
            <label for="is_subscribed" class="label"><span><?php /* @escapeNotVerified */ echo __('Subscribe 2XL Newsletter') ?></span></label>
            </div>
        </div>

    </div>
    </fieldset>
    <?php if ($block->getShowAddressFields()): ?>
        <fieldset class="fieldset address">
            <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Address Information') ?></span></legend><br>
            <input type="hidden" name="create_address" value="1" />
            <div class="field company">
                <label for="company" class="label"><span><?php /* @escapeNotVerified */ echo __('Company') ?></span></label>
                <div class="control">
                    <input type="text" name="company" id="company" value="<?php echo $block->escapeHtml($block->getFormData()->getCompany()) ?>" title="<?php /* @escapeNotVerified */ echo __('Company') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
                </div>
            </div>
            <div class="field telephone">
                <label for="telephone" class="label"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
                <div class="control">
                    <input type="text" name="telephone" id="telephone" value="<?php echo $block->escapeHtml($block->getFormData()->getTelephone()) ?>" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>">
                </div>
            </div>

            <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

            <div class="field street required">
                <label for="street_1" class="label"><span><?php /* @escapeNotVerified */ echo __('Street Address') ?></span></label>
                <div class="control">
                    <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getFormData()->getStreet(0)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" id="street_1" class="input-text validate-customstreet <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                    <div class="nested">
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                            <div class="field additional">
                                <label class="label" for="street_<?php /* @escapeNotVerified */ echo $_i ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Address') ?></span>
                                </label>
                                <div class="control">
                                    <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getFormData()->getStreetLine($_i - 1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i) ?>" id="street_<?php /* @escapeNotVerified */ echo $_i ?>" class="input-text <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>

            <div class="field required">
                <label for="city" class="label"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
                <div class="control">
                    <input type="text" name="city" value="<?php echo $block->escapeHtml($block->getFormData()->getCity()) ?>" title="<?php /* @escapeNotVerified */ echo __('City') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city">
                </div>
            </div>

            <div class="field region required">
                <label for="region_id" class="label"><span><?php /* @escapeNotVerified */ echo __('State/Province') ?></span></label>
                <div class="control">
                    <select id="region_id" name="region_id" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="validate-select" style="display:none;">
                        <option value=""><?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?></option>
                    </select>
                    <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getRegion()) ?>" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="input-text <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>" style="display:none;">
                </div>
            </div>

            <div class="field zip required">
                <label for="zip" class="label"><span><?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?></span></label>
                <div class="control">
                    <input type="text" name="postcode" value="<?php echo $block->escapeHtml($block->getFormData()->getPostcode()) ?>" title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
                </div>
            </div>

            <div class="field country required">
                <label for="country" class="label"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
                <div class="control">
                    <?php echo $block->getCountryHtmlSelect() ?>
                </div>
            </div>
            <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
            <?php if ($addressAttributes): ?>
                <?php $addressAttributes->setEntityType('customer_address'); ?>
                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                <?php echo $addressAttributes->setShowContainer(false)->toHtml()?>
            <?php endif;?>
            <input type="hidden" name="default_billing" value="1">
            <input type="hidden" name="default_shipping" value="1">
        </fieldset>

    <?php endif; ?>
        <?php echo $block->getChildHtml('form_additional_info'); ?>
                <?php if ($block->isNewsletterEnabled()): ?>

            <?php /* Extensions placeholder */ ?>
            <?php echo $block->getChildHtml('customer.form.register.newsletter')?>
        <?php endif ?>

    <div class="actions-toolbar">
            <button type="submit" class="action submit primary register_form_bttn" title="<?php /* @escapeNotVerified */ echo __('Create Account') ?>"><span><?php /* @escapeNotVerified */ echo __('Create Account') ?></span></button>
            <!-- <a class="action back" href="<?php //echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ //echo __('Back') ?></span></a> -->
    </div>

</form>
<script>
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#form-validate');
    var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;

    dataForm.mage('validation', {
    <?php if ($_dob->isEnabled()): ?>
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
    <?php else: ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    <?php endif ?>
    }).find('input:text').attr('autocomplete', 'off');

});
</script>
<?php if ($block->getShowAddressFields()): ?>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php endif; ?>



<script type="text/javascript">

require([
    'jquery'
], function($){
        var baseurl_action = '<?php echo $Baseurl; ?>'+'carriercodetelephone/telephonevalidation/';
        $.ajax({
       url: baseurl_action,
       data: {
          format: 'json'
       },
       error: function() {
          console.log('Some error as been ocuured');
       },
       success: function(data) {
          var obj = jQuery.parseJSON(data);
          obj = jQuery.unique(obj);
            /*$('select#country_code').append($('<option>', {
                value: '',
                text: ''
            }));*/

          for (i = 0; i < obj.length; i++) {
                        $('select#country_code').append($('<option>', {
                            value: obj[i],
                            text: '+'+obj[i]
                        }));
            }

       },
       type: 'GET'
    });

        $('select#country_code').change(function(){

            var country_code = jQuery('select#country_code').val();
            var baseurl_action =  '<?php echo $Baseurl; ?>'+'carriercodetelephone/telephonevalidation/carriercode/'

                 $.ajax({
               url: baseurl_action ,
               data: {
                  format: 'json',
                  country_code : country_code
               },
               error: function() {
                  console.log('Some error as been ocuured');
               },
               success: function(data) {
                  var obj = jQuery.parseJSON(data);
                  obj = jQuery.unique(obj);

                  $('select#carrier_code').removeAttr("selected");
                  $('select#carrier_code').empty();
                  if (obj.length === 0) {

                        $('select#carrier_code').append($('<option>', {
                                    value: '',
                                    text: 'Carrier Code'
                                }));
                    }else{

                      for (i = 0; i < obj.length; i++) {
                                    $('select#carrier_code').append($('<option>', {
                                        value: obj[i],
                                        text: obj[i]
                                    }));
                        }
                    }
               },
               type: 'GET'
            });
        });

        $('button.register_form_bttn').click(function(){
            var country_code = jQuery.trim($('select#country_code').val());
            var carrier_code = jQuery.trim($('select#carrier_code').val());
            var tele_number = jQuery.trim($('input#tele_number').val());
            $('input#account_telephone').val(country_code+'-'+carrier_code+'-'+tele_number);
            $('form.form-create-account').submit();

        });

});

</script>

<script type="text/javascript">
require([
    'jquery',
    'mage/mage'
], function($){

   var dataForm = $('.form-create-account');
   dataForm.mage('validation', {});

});
</script>
