<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block discount clear" id="block-discount">
    <div class="coupon_title" data-role="title">
        <?php /* @escapeNotVerified */ echo __('Enter Coupon Code') ?>
    </div>
    <div class="coupon_content clear" data-role="content" aria-labelledby="block-discount-heading">
        <form id="discount-coupon-form"
              action="<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/cart/couponPost') ?>"
              method="post"
              data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                                               "removeCouponSelector": "#remove-coupon",
                                               "applyButton": "button.action_cart",
                                               "cancelButton": "button.action_cart.cancel"}}'>
            <div class="fieldset coupon<?php strlen($block->getCouponCode()) ? ' applied' : ''?>">
                <input type="hidden" name="remove" id="remove-coupon" value="0" />
                <div class="field">
                    <div class="control">
                        <input type="text" class="input-text" id="coupon_code" name="coupon_code" value="<?php echo $block->escapeHtml($block->getCouponCode()) ?>" placeholder="<?php echo $block->escapeHtml(__('Coupon Code'));?>" />
                    </div>
                </div>
                <div class="actions-toolbar">
                    <?php if (!strlen($block->getCouponCode())): ?>
                    <div class="">
                        <button class="action_cart" type="button" value="<?php /* @escapeNotVerified */ echo __('Apply') ?>">
                            <span><?php /* @escapeNotVerified */ echo __('Apply') ?></span>
                        </button>
                    </div>
                    <?php else: ?>
                        <div class="">
                            <button  type="button" class="action_cart cancel" value="<?php /* @escapeNotVerified */ echo __('Cancel') ?>"><span><?php /* @escapeNotVerified */ echo __('Cancel') ?></span></button>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </form>
    </div>
</div>
