<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="cart-empty">
    <?php echo $block->getChildHtml('checkout_cart_empty_widget'); ?>
    <span class="empty_cart_icon"></span>
    <h3><?php /* @escapeNotVerified */ echo __('Your shopping cart is empty') ?></h3>
    <p><?php /* @escapeNotVerified */ echo __('<a href="%1" class="cart_btn">continue shopping</a>',
            $block->escapeUrl($block->getContinueShoppingUrl())) ?></p>
    <?php echo $block->getChildHtml('shopping.cart.table.after'); ?>
</div>
