<?php $columnsLimit = $block->getColumnsLimit() ? : 0; ?>
<?php $_menu2 = $block->getHtml('level-top', 'mega', $columnsLimit) ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php if ($block->allowExtension()): ?>
    <script>

        require([
            'jquery',
            'ibnabmodernizr'
        ], function ($) {


            $('.menu > ul > li:has( > ul)').addClass('menu-dropdown-icon');
            //Checks if li has sub (ul) and adds class for toggle icon - just an UI


            $('.menu > ul > li > ul:not(:has(ul))').addClass('normal-sub');
            //Checks if drodown menu's li elements have anothere level (ul), if not the dropdown is shown as regular dropdown, not a mega menu (thanks Luka Kladaric)

            //$(".page-header .logo").before("<a href=\"#\" class=\"menu-mobile\"></a>");

            //Adds menu-mobile class (for mobile toggle menu) before the normal menu
            //Mobile menu is hidden if width is more then 959px, but normal menu is displayed
            //Normal menu is hidden if width is below 959px, and jquery adds mobile menu
            //Done this way so it can be used with wordpress without any trouble
            $('.menu > ul.menu_l1 > li').hover(function(event) {
                event.preventDefault();

                if ($(window).width() > 1024) {

                    var get_state = $(this).find("> ul").css("display");
                    var this_el = $(this);
                    if(get_state == "none"){
                        this_el.children("ul").stop(true,false).slideDown(); 
                        $(".menu-nav-overlay").show();
                        equalheight('.menu ul li ul li.level1');
                    }else{
                        $(".menu > ul > li > ul").stop(true,false).hide();
                        $(".menu-nav-overlay").hide();
                        equalheight('.menu ul li ul li.level1');

                    }                        

                }

            })
            //If width is more than 943px dropdowns are displayed on hover


            /*$(".menu > ul > li").hover(function (e) {
                var submenu_status = $(this).children("ul").css("display");
                if(submenu_status == "block"){
                    $(".menu-nav-overlay").show();
                }
                if(submenu_status == "none"){
                    $(".menu-nav-overlay").hide();
                }
                event.stopImmediatePropagation()
            });*/

            $(".menu > ul > li").click(function () {
                if ($(window).width() <= 1024) {
                    $(this).children("ul").fadeToggle(150);
                }
            });
            //If width is less or equal to 943px dropdowns are displayed on click (thanks Aman Jain from stackoverflow)

            $(".menu-mobile").click(function (e) {
                $(".menu > ul").toggleClass('show-on-mobile');
                e.preventDefault();
            });

            $('.menu-dropdown-icon').click(function(){
                $(this).toggleClass('arrow-down');
            });


            $( "ul.normal-sub" ).each(function() {
              if($(this).has('li').length == 0){
                  $( this ).remove();
                }
            });



        });

    </script>
    <?php
    /**
     * Top menu for store
     *
     * @see \Magento\Theme\Block\Html\Topmenu
     */
    ?>
    <nav class="navigation" role="navigation" >

        <div class="menu" id="om">
            <h1>Menu</h1>
            <span class="menu_close"></span>
            <ul class="menu_l1">
                <?php /* @escapeNotVerified */ echo $_menu2; ?>
            </ul>
        </div>
        <!-- <ul id="dm" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <?php /* @escapeNotVerified */ //echo $_menu; ?>
        </ul> -->
    </nav>

<?php else : ?>

    <nav class="navigation" role="navigation">
<?php /* @escapeNotVerified */ echo $_menu; ?>
    </nav>
<?php endif; ?>