<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
    $_order  = $block->getOrder();
    $_source = $block->getSource();
    $_fullInfo = $this->helper('Magento\Tax\Helper\Data')->getCalculatedTaxes($_source);
    global $taxIter; $taxIter++;
?>
<?php if ($_fullInfo && $block->displayFullSummary()): ?>
        <?php foreach ($_fullInfo as $info): ?>full
            <?php
                $percent    = $info['percent'];
                $amount     = $info['tax_amount'];
                $baseAmount = $info['base_tax_amount'];
                $title      = $info['title'];
            ?>
            <tr class="totals tax details details-<?php /* @escapeNotVerified */ echo $taxIter; ?> <?php echo($block->getIsPlaneMode()) ? ' plane' : '';?>">
                <td <?php /* @escapeNotVerified */ echo $block->getLabelProperties()?>>
                    <?php echo $block->escapeHtml($title); ?>
                    <?php if (!is_null($percent)): ?>
                        (<?php echo (float)$percent; ?>%)
                    <?php endif; ?>
                    <br />
                </td>
                <td <?php /* @escapeNotVerified */ echo $block->getValueProperties()?> rowspan="1">
                    <?php /* @escapeNotVerified */ echo $_order->formatPrice($amount); ?>
                </td>
            </tr>
        <?php endforeach; ?>
<?php endif;?>
<?php /* ?>
<?php if ($block->displayFullSummary() && $_fullInfo && !$block->getIsPlaneMode()): ?>
<tr class="totals-tax-summary">
<?php elseif ($block->displayFullSummary() && $_fullInfo && $block->getIsPlaneMode()): ?>
<tr class="totals-tax-summary plane">
<?php else: ?>
<tr class="totals-tax">
<?php endif; ?>
    <th <?php  echo $block->getLabelProperties()?> scope="row">
        <?php if ($block->displayFullSummary()): ?>
            <div class="detailed"><?php  echo __('Tax 11'); ?></div>
        <?php else: ?>
            <?php  echo __('Tax 222'); ?>
        <?php endif;?>
    </th>
    <td <?php  echo $block->getValueProperties()?> data-th="<?php echo $block->escapeHtml(__('Tax 333')); ?>">
        <?php echo $_order->formatPrice($_source->getTaxAmount()) ?>
    </td>
</tr>
<?php */ ?>

<tr>
    <td valign="top" style="font-size:12px;padding:5px 0 0px" align="right"> 
        <table border="0" cellspacing="0" cellpadding="0" width="220">
            <tr>
                <td valign="top" style="font-size:11px;padding:0;font-family:Open Sans,Verdana;" align="left" width="50%">
                    VAT:
                </td>
                <td valign="top" style="font-size:11px;padding:0;font-family:Open Sans,Verdana;" align="left">
                <?php echo $_order->formatPrice($_source->getTaxAmount()) ?>    
                </td>
            </tr>
        </table>
    </td>
</tr>