<div class="largeSlider">
    <?php
    $image_cnt = count($block->getGalleryImages());
    $galleryImageJson = json_decode($block->getGalleryImagesJson());
    if($image_cnt > 0){
    foreach($galleryImageJson as $image){ ?>
        <?php //if($block->isMainImage($image)):?>
            <li  class="ex1" data-src="<?php echo $image->full; ?>"><img src="<?php echo $image->full; ?>"></li>
        <?php //endif; ?>
    <?php }
    }
    else { 
    $imageUrl = $block->getImage($block->getProduct(), 'category_page_grid')->getImageUrl(); ?>
    <li><img src="<?php echo $imageUrl; ?>"></li>
    <?php } ?>
</div>
<div class="thumb_wrapper">
<div class="thumbSlider">
    <?php
    foreach($galleryImageJson as $image){ ?>
        <?php //if(!$block->isMainImage($image)):?>
            <li><img src="<?php echo $image->thumb; ?>"></li>
        <?php //endif; ?>
    <?php } ?>
</div>
</div>
<script type="text/javascript">
  require(['jquery', 'slick'], function($){
    $(document).ready(function(){
      $('.largeSlider').slick({
        slidesToShow: 1,
        slidesToScroll: 1,
        arrows: true,
        asNavFor: '.thumbSlider'
      });
      $('.thumbSlider').slick({
        slidesToShow: 4,
        slidesToScroll: 1,
        arrows: true,
        asNavFor: '.largeSlider',
        focusOnSelect: true,
        responsive: [
            {
                breakpoint: 800,
                settings: {
                slidesToShow:3,
                }
            },
            {
                breakpoint: 480,
                settings: {
                slidesToShow:1,
                }
            }
        ]
      });
    });
  });
require(['jquery'], function($){
    require(['minzoo'], function(){
        $(document).ready(function(){
            if ($(window).width() > 1024) {
                $('.ex1').zoom();
              }
        });
    })
});

</script>