<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Order\Items $block */
$order_id = $block->getOrder()->getId();
//$invoice_downloadurl =

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$order_state = $block->getOrder()->getState();
$aOrderStateAllow = array('delivered' , 'complete');


$invoice_downloadurl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB).'myaccount/account/invoicedownload/order_id/'.$order_id;
?>
	<div class="view_order_wrapper">
	
		
            <?php $items = $block->getItems(); ?>
            <?php $giftMessage = ''?>
            <?php foreach ($items as $item): ?>
                <?php if ($item->getParentItem()) continue; ?>
                <div class="view_order_row clear">
                <?php echo $block->getItemHtml($item) ?>
                <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item', $item) && $item->getGiftMessageId()): ?>
                    <?php $giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($item); ?>
                    <div class="order_options">
                        <div class="col options" colspan="5">
                            <a href="#"
                                id="order-item-gift-message-link-<?php /* @escapeNotVerified */ echo $item->getId() ?>"
                                class="action show"
                                aria-controls="order-item-gift-message-<?php /* @escapeNotVerified */ echo $item->getId() ?>"
                                data-item-id="<?php /* @escapeNotVerified */ echo $item->getId() ?>">
                                <?php /* @escapeNotVerified */ echo __('Gift Message') ?>
                            </a>
                            <?php $giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($item); ?>
                            <div class="order-gift-message" id="order-item-gift-message-<?php /* @escapeNotVerified */ echo $item->getId() ?>" role="region" aria-expanded="false" tabindex="-1">
                                <a href="#"
                                   title="<?php /* @escapeNotVerified */ echo __('Close') ?>"
                                   aria-controls="order-item-gift-message-<?php /* @escapeNotVerified */ echo $item->getId()?>"
                                   data-item-id="<?php /* @escapeNotVerified */ echo $item->getId()?>"
                                   class="action close">
                                    <?php /* @escapeNotVerified */ echo __('Close') ?>
                                </a>
                                <dl class="item-options">
                                    <dt class="item-sender"><strong class="label"><?php /* @escapeNotVerified */ echo __('From') ?></strong><?php echo $block->escapeHtml($giftMessage->getSender()) ?></dt>
                                    <dt class="item-recipient"><strong class="label"><?php /* @escapeNotVerified */ echo __('To') ?></strong><?php echo $block->escapeHtml($giftMessage->getRecipient()) ?></dt>
                                    <dd class="item-message"><?php /* @escapeNotVerified */ echo $this->helper('Magento\GiftMessage\Helper\Message')->getEscapedGiftMessage($item) ?></dd>
                                </dl>
                            </div>
                        </div>
                    </div>
                <?php endif ?>
                </div>
            <?php endforeach; ?>

            <tfoot>
            <?php if($block->isPagerDisplayed()): ?>
                <tr>
                    <td colspan="5" data-block="order-items-pager-bottom" class="order-pager-wrapper order-pager-wrapper-bottom">
                        <?php echo $block->getPagerHtml();?>
                    </td>
                </tr>
            <?php endif ?>
            <?php echo $block->getChildHtml('order_totals') ?>
            </tfoot>

	</div>







<?php if ($giftMessage): ?>
    <script type="text/x-magento-init">
    {
        "a.action.show, a.action.close": {
            "giftMessage": {}
        }
    }
</script>
<?php endif; ?>

<script>

  // require([
  //   'jquery',
  //   'mage/validation'
  //   ], function($){ 

  //     $('.return_sbmt').on('click',function(){
	 //      var sub_order_id = [];
  //           $.each($("input[name='return_chk']:checked"), function(){            
  //               sub_order_id.push($(this).val());
  //           });
  //           console.log(sub_order_id);
  //           jQuery.ajax({
	 //        data: {                 
	 //                'sub_order_id': sub_order_id, 
	 //              },
	 //        dataType:'json',
	 //        url: "<?php //echo $this->getUrl('orderreturns/returns/index'); ?>",
	 //        method:'post',
	 //        showLoader: true,
	 //        success:function(resp){
	 //          location.reload(); 
	 //        }
	 //      });
	 //   });
  // });
</script>
<script type="text/javascript">


	function downloadInvoice(invoice_url){

		window.location = invoice_url;
		return false;
	}

</script>
<div class="return_btn">
<?php if(in_array($order_state , $aOrderStateAllow)){ ?>
        <button type="button" name="invoice_down" onclick="downloadInvoice('<?php echo $invoice_downloadurl; ?>');" value="Invoice Download" class="action primary invoice_btn">Invoice</button>
<?php } ?>
</div>

