<?php

//$orderId = $this->getData('orderId');
/*
$orderId = 114;
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_order = $objectManager->create('Magento\Sales\Model\Order')->load($orderId);
$payment = $_order->getPayment();
$method = $payment->getMethodInstance();
$methodTitle = $method->getTitle();
$shippingAddress = $_order->getShippingAddress();
$increment_id = $_order->getIncrementId();
$currency_code = $_order->getOrderCurrencyCode();
?>
<?php $_items = $_order->getAllItems();  ?>

<?php if ($_order): ?>
<?php $order_date = $_order->getCreated_at();
$order_date_format = date('F d, Y', strtotime($order_date));
 ?>
<tr>                    
    <td valign="top" style="padding:5px 0 25px 0">
        <table border="0" cellspacing="0" cellpadding="0" width="100%">
            <tr>
                <td valign="top" style="font-size:12px;" align="left" width="60%">
                    <table border="0" cellspacing="0" cellpadding="0" >
                        <tr>
                            <td valign="top" style="font-size:12px;padding:0 0;font-family:Open Sans,Verdana;"><strong>RETURNS</strong></td>
                        </tr>
                        <tr>
                            <td valign="top" style="font-size:12px;padding:5px 0 0;font-family:Open Sans,Verdana;"><strong>Order Id:</strong> <?php echo $orderId; ?></td>
                        </tr>
                        <tr>
                            <td valign="top" style="font-size:12px;padding:5px 0 0;font-family:Open Sans,Verdana;"><strong>Order Date :</strong> <?php echo $order_date_format; ?></td>
                        </tr>
                        <tr>
                            <td valign="top" style="font-size:12px;padding:5px 0 0;font-family:Open Sans,Verdana;"><strong>Payment Method :</strong>  <?php echo $methodTitle; ?></td>
                        </tr>
                        <tr>
                            <td valign="top" style="font-size:12px;padding:5px 0 0;font-family:Open Sans,Verdana;"><strong>Items :</strong> <?php echo count($_items); ?></td>
                        </tr>
                    </table>
                </td>
                <td valign="top" style="font-size:12px;line-height:16px;font-family:Open Sans,Verdana;" align="">
                    <strong style="font-size:12px;"> Shipping Address</strong><br/>
                    <?php
                        echo $shippingAddress->getFirstname()." ".$shippingAddress->getLastname()."<br>"; 
                        echo $shippingAddress->getRegion()."<br>";                    
                        $countryCode = $shippingAddress->getCountryId();
                        $country = $objectManager->create('\Magento\Directory\Model\Country')->load($countryCode)->getName();
                        echo $shippingAddress->getCity().", ".$country."<br>";
                        echo "Phone: ".$shippingAddress->getTelephone();
                    ?>
                </td>
                
            </tr>
        </table>
    </td>
</tr>

<tr>                    
    <td valign="top" style="padding:0px 0;font-family:Open Sans,Verdana;border-bottom:2px solid #000;border-top:2px solid #000">
        <table border="0" cellspacing="0" cellpadding="0" width="100%">
            <tr>
                <td valign="top" style="font-size:12px;border-bottom:1px solid #000;text-align:center;padding:7px 0;font-family:Open Sans,Verdana;" align="left" width="25%">
                    Items Ordered
                </td>
                <td valign="top" style="font-size:12px;border-bottom:1px solid #000;text-align:center;padding:5px 0;font-family:Open Sans,Verdana;" align="" width="45%">
                    &nbsp;
                </td>   
                <td valign="top" style="font-size:12px;border-bottom:1px solid #000;text-align:center;padding:5px 0;font-family:Open Sans,Verdana;" align="" >
                    Price
                </td>                           
            </tr>
            <?php foreach ($_items as $_item): ?> 
            <?php

                $prdId = $_item['product_id'];
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $product = $objectManager->get('Magento\Catalog\Model\Product')->load($prdId);
                $store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
                $image = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $product->getThumbnail();

                $product_color = $product->getAttributeText('product_color');
            ?> 
            <tr>
                <td valign="top" style="font-size:12px;padding:15px;font-family:Open Sans,Verdana;" align="left">
                    <img src="<?php echo $image; ?>" width="112" />
                </td>
                <td valign="top" style="font-size:12px;padding:15px;font-family:Open Sans,Verdana;">
                    <table border="0" cellspacing="0" cellpadding="0" width="100%">
                        <tr>
                            <td valign="top" style="font-size:12px;padding:0;font-family:Open Sans,Verdana;" align="left" width="30%">
                                <strong>Sub-Order Id: <?php echo $_item['item_id']; ?></strong>
                            </td>
                        </tr>
                        <tr>
                            <td valign="top" style="font-size:12px;padding:0;font-family:Open Sans,Verdana;" align="">
                                <strong><?php echo $_item['name']; ?></strong>
                            </td>   
                        </tr>
                        <tr>
                            <td valign="top" style="font-size:12px;padding:0;font-family:Open Sans,Verdana;" align="left" width="30%">
                                <strong>Item Code:</strong> <?php echo $_item['sku']; ?>
                            </td>
                        </tr>
                        <tr>
                            <td valign="top" style="font-size:12px;padding:0;font-family:Open Sans,Verdana;" align="">
                                <strong>Qty:</strong> <?php echo $_item['qty_ordered']; ?>
                            </td>   
                        </tr>
                        <?php if($product_color != ''): ?>
                        <tr>
                            <td valign="top" style="font-size:12px;padding:0;font-family:Open Sans,Verdana;" align="">
                                <strong>Colour:</strong> <?php echo $product_color; ?>
                            </td>                           
                        </tr>
                        <?php endif; ?>
                    </table>
                </td>   
                <td valign="top" style="font-size:12px;text-align:center;padding:15px 0 0 ;font-family:Open Sans,Verdana;" align="">
                    <?php echo $currency_code." ".round($_item['price'],2); ?>
                </td>                           
            </tr>
            <?php endforeach; ?>
        </table>
    </td>
</tr>
<tr>
    <td valign="top" style="font-size:12px;padding:5px 0 10px" align="right">
        <table border="0" cellspacing="0" cellpadding="0" width="220">
        <?php
            $subtotal = $_order->getSubtotal();
            $shipping_handling = $_order->getShippingAmount();
            $tax_amount = $_order->getTax_amount();
            $grand_total = $_order->getGrandTotal();
            
            $discount_amount = $_order->getDiscountAmount();            
        ?>
                <td valign="top" style="font-size:12px;" width="50%"> 
                    <table border="0" cellspacing="0" cellpadding="0" width="100%">
                        <tr>
                            <td valign="top" style="font-size:12px;padding:0;font-family:Open Sans,Verdana;" align="left" width="30%">
                                Product Subtotal:
                            </td>
                        </tr>
                        <tr>
                            <td valign="top" style="font-size:12px;padding:0;font-family:Open Sans,Verdana;" align="">
                                 Shipping Charges: 
                            </td>   
                        </tr>
                        <tr>
                            <td valign="top" style="font-size:12px;padding:0;font-family:Open Sans,Verdana;" align="left" width="30%">
                                VAT:
                            </td>
                        </tr>
                        <tr>
                            <td valign="top" style="font-size:12px;padding:0 0 5px;font-family:Open Sans,Verdana;" align="">
                            Discount:
                            </td>   
                        </tr>
                        <tr>
                            <td valign="top" style="font-size:12px;padding:3px 0;font-family:Open Sans,Verdana;border-bottom:1px solid #000;border-top:1px solid #000" align="">
                                <strong>Grand Total:</strong>
                            </td>                           
                        </tr>
                    </table>
                </td>

                <td valign="top" style="font-size:12px;"> 
                    <table border="0" cellspacing="0" cellpadding="0" width="100%">
                        <tr>
                            <td valign="top" style="font-size:12px;padding:0;font-family:Open Sans,Verdana;" align="left" width="30%">
                                <?php echo $currency_code." ".round($subtotal,2); ?>
                            </td>
                        </tr>
                        <tr>
                            <td valign="top" style="font-size:12px;padding:0;font-family:Open Sans,Verdana;" align="">
                                 <?php echo $currency_code." ".round($shipping_handling,2); ?>
                            </td>   
                        </tr>
                        <tr>
                            <td valign="top" style="font-size:12px;padding:0;font-family:Open Sans,Verdana;" align="left" width="30%">
                               <?php echo $currency_code." ".round($tax_amount,2); ?>
                            </td>
                        </tr>
                        <tr>
                            <td valign="top" style="font-size:12px;padding:0 0 5px;font-family:Open Sans,Verdana;" align="">
                                <?php echo $currency_code." ".round($discount_amount,2); ?>
                            </td>   
                        </tr>
                        <tr>
                            <td valign="top" style="font-size:12px;padding:3px 0;font-family:Open Sans,Verdana;border-bottom:1px solid #000;border-top:1px solid #000" align="">
                                <strong> <?php echo $currency_code." ".round($grand_total,2); ?> </strong>
                            </td>                           
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </td>
</tr>
<?php endif; */?>