<?php
$object_manager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $object_manager->get('Magento\Customer\Model\Session');
$helper = $object_manager->get('Emipro\Ticketsystem\Helper\Data');

$storeId=$helper->getCurrentStoreId();
$attachmentSize=$helper->getConfig('emipro/general/attachment_size',$storeId);
if($attachmentSize!=0 && $attachmentSize!=""){
	$maxfile_size=$attachmentSize;
}else{
	$maxfile_size = "4";
}
?>
<div class="primary cus-link back_link">
	<a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Back') ?></span></a>
</div>
<form class="form form-edit-account create_support_ticket" action="<?php echo $block->getSaveUrl() ?>" id="ticketForm" 	method="post" 
    enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset info">
        <?php echo $block->getBlockHtml('formkey') ?>
        <?php if (!$customerSession->isLoggedIn()): ?>
            <div class="field name required">
                <div class="control">
                    <input name="customer_name" id="name" title="<?php echo __('Name') ?>"   class="input-text" type="text" data-validate="{required:true}" placeholder="Name"/>
                </div>
            </div>
            <div class="field name required">
                <div class="control">
                    <input name="customer_email" id="mail" title="<?php echo __('Email') ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}" placeholder="Email"/>
                </div>
            </div>
        <?php endif; ?>    
        <div class="field name required">
            <div class="control">
                <select class="validate-select" title="<?php echo __('Department') ?>" name="department_id" id="department_id">
                    <option value=""><?php echo __('Please Select Department'); ?></option>
                    <?php $department = $helper->getTicketdept();
                    foreach ($department as $key => $value): ?>
                        <option value=<?php echo $key; ?>><?php echo __($value); ?></option>
					<?php endforeach; ?>
                </select>
			</div>
        </div>
        <div class="field name required">
            <div class="control">
                <select class="validate-select" title="<?php echo __('Priority') ?>" name="priority_id" id="priority_id">
                    <option value=""><?php echo __('Please Select Priority'); ?></option>
                    <?php $priority = $helper->getTicketpriority();
                    foreach ($priority as $key => $value) { ?>
                        <option value=<?php echo $key; ?>><?php echo __($value); ?></option>
                     <?php } ?>
                </select>
            </div>
        </div>
        <div class="field name ">
            <div class="input-box">
				<?php if ($customerSession->isLoggedIn()): 
					$customerId = $customerSession->getId(); 
					$allOrderIds=$helper->getCustomerOrderIds($customerId); ?>
					<select id="orderid" name="orderid" title="<?php echo __('Set Order Id') ?>">
						<option value=""><?php echo __('please select Order Id'); ?></option>
						<?php foreach($allOrderIds as $key=>$orderid){ ?>
							<option value="<?php echo $key ?>"><?php echo $orderid ?></option>
						<?php } ?>
					</select>
				<?php else: ?>
					<input name="orderid" id="orderid" title="<?php echo __('Order Id') ?>"   type="text"  class="input-text" placeholder="Order Id" />
				<?php endif; ?>
            </div>
        </div>
        <div class="field subject required">
            <div class="control">
                <input name="subject" id="subject" title="<?php echo __('Subject') ?>"  class="input-text" type="text" data-validate="{required:true}" placeholder="Subject" />
            </div>
        </div>
        <div class="field message required">
            <div class="control">
                <textarea name="message" id="message" title="<?php echo __('Message') ?>" class="required-entry input-text support_textarea" cols="5" rows="3"  data-validate='{required:true}' placeholder="Message"></textarea>
            </div>
        </div>
        <div class="field" id="attach-msg">
			<div class="choose_file" id="attach_file">
                <!-- <label id="uploadFile"></label> -->
                <input id="uploadBtn" name="file" type="file" class="validate-filesize">
            </div>
        </div>    
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action save primary" title="<?php /* @escapeNotVerified */ echo __('Submit Ticket') ?>"><span><?php /* @escapeNotVerified */ echo __('Submit Ticket') ?></span></button>
            </div>
        </div>       
        <input type="hidden" name="customer_id" value="<?php echo $customerSession->getId(); ?>" id="customer_id">
</form>
<script>
    
    document.getElementById("uploadBtn").onchange = function () 
    {
        document.getElementById("uploadFile").innerHTML = this.value;
    }
</script>
<script type="text/javascript">
require(['jquery','jquery/ui','jquery/validate','mage/translate'], function($){ 
	$.validator.addMethod(
		'validate-filesize', function (v, elm) {
			var maxSize = <?php echo $maxfile_size ?> * 1024 * 1024;

            if (navigator.appName == "Microsoft Internet Explorer") {
				if (elm.value) {
					var oas = new ActiveXObject("Scripting.FileSystemObject");
                    var e = oas.getFile(elm.value);
                    var size = e.size;
                }
            } else {
				if (elm.files[0] != undefined) {
					size = elm.files[0].size;
                }
            }
           
            if (size != undefined && size > maxSize) {
				return false;
            }
            return true;
        }, $.mage.__('The file size should not exceed <?php echo $maxfile_size ?>MB')
    );
});
</script>
