<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper('Magento\Msrp\Helper\Data');
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<div class="cart item message error" style="display:none;" id="div_error">Please remove out of stock product.</div>
<div class="cart-item clear">

        <div class='product-image'>
            <?php if ($block->hasProductUrl()):?>
                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"
                   title="<?php echo $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1">
            <?php else:?>
            <?php endif;?>
                <?php echo $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml(); ?>
                <?php if ($block->hasProductUrl()):?>
                </a>
                <?php else: ?>
            <?php endif; ?>
        </div>
        <div class="item-info">
            <div class="item-details">
                    <div class="item-name">
                        <?php if ($block->hasProductUrl()):?>
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl() ?>"><?php echo $block->escapeHtml($block->getProductName()) ?></a>
                        <?php else: ?>
                            <?php echo $block->escapeHtml($block->getProductName()) ?>
                        <?php endif; ?>
                    </div>
                    <?php if ($_options = $block->getOptionList()):?>
                        <dl class="item-options">
                            <?php foreach ($_options as $_option) : ?>
                                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                <dt><?php echo $block->escapeHtml($_option['label']) ?></dt>
                                <dd>
                                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                        <?php /* @escapeNotVerified */ echo $_formatedOptionValue['full_view'] ?>
                                    <?php else: ?>
                                        <?php /* @escapeNotVerified */ echo $_formatedOptionValue['value'] ?>
                                    <?php endif; ?>
                                </dd>
                            <?php endforeach; ?>
                        </dl>
                    <?php endif;?>
                    <?php if ($messages = $block->getMessages()): ?>
                        <?php foreach ($messages as $message): ?>
                            <div class="cart item message <?php /* @escapeNotVerified */ echo $message['type'] ?>"><div id="div_error_msg"><?php echo $block->escapeHtml($message['text']) ?></div></div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                    <?php if ($addInfoBlock): ?>
                        <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
                    <?php endif;?>
            </div>
            <div class="sku_txt">
                <span class="cart_label">SKU:</span><span><?php echo $_item->getSku(); ?></span>
            </div>

            <div class="field_qty">
                <label class="label cart_label" for="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty">
                    <?php /* @escapeNotVerified */ echo __('Qty:') ?>
                </label>
                <div class="control qty">
                    <?php $qty = $block->getQty();?>
                        <select id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
                               name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                               data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
                               title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                               data-role="cart-item-qty">
                               <?php for($i=1;$i<=10;$i++){ ?>
                                 <option value="<?php echo $i; ?>" <?php if($i == $qty) echo 'selected';?> ><?php echo $i ?></option>
                               <?php } ?>
                    </select>
                </div>
            </div>
            <!--td class="col subtotal" data-th="<?php //echo $block->escapeHtml(__('Subtotal twoxk'));?>">
                <?php //if ($canApplyMsrp): ?>
                    <span class="cart msrp subtotal"> </span>
                <?php //else: ?>
                    <?php //echo $block->getRowTotalHtml($_item); ?>
                <?php //endif; ?>
            </td-->

            <div class="mob_price">
                        <div class="price">
        <?php if ($canApplyMsrp): ?>     
            <span class="pricing msrp">
            <span class="msrp notice"><?php /* @escapeNotVerified */ echo __('See price before order confirmation.'); ?></span>
            <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
            <a href="#" class="action help map" id="<?php /* @escapeNotVerified */ echo($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */ echo $helpLinkId;?>","productName": "<?php /* @escapeNotVerified */ echo $product->getName(); ?>","showAddToCart": false}}'>
            <span><?php /* @escapeNotVerified */ echo __("What's this?"); ?></span>
            </a>
            </span>

        <?php else: ?>
            <?php //echo $block->getUnitPriceHtml($_item); ?> 
            <?php echo $block->getRowTotalHtml($_item); ?>   
        <?php endif; ?>
        </div>
            </div>

        </div>

        <div class="cart_right_info">
        <div class="item-actions">
            <div class="actions-toolbar">
                <?php /* @escapeNotVerified */ echo $block->getActions($_item) ?>
            </div>        
        </div>

        <div class="price">
        <?php if ($canApplyMsrp): ?>     
            <span class="pricing msrp">
            <span class="msrp notice"><?php /* @escapeNotVerified */ echo __('See price before order confirmation.'); ?></span>
            <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
            <a href="#" class="action help map" id="<?php /* @escapeNotVerified */ echo($helpLinkId); ?>" data-mage-init='{"addToCart":{"helpLinkId": "#<?php /* @escapeNotVerified */ echo $helpLinkId;?>","productName": "<?php /* @escapeNotVerified */ echo $product->getName(); ?>","showAddToCart": false}}'>
            <span><?php /* @escapeNotVerified */ echo __("What's this?"); ?></span>
            </a>
            </span>

        <?php else: ?>
            <?php //echo $block->getUnitPriceHtml($_item); ?>
            <?php echo $block->getRowTotalHtml($_item); ?>
        <?php endif; ?>
        </div>
        </div>    
</div>
