<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="checkout-failure">
	<div class="checkout_fail_icon"></div>
	<h2>Sorry!</h2>
	<p class="order_txt">We are unable to process your payment</p>
	<?php if ($block->getRealOrderId()) : ?><p class="order_txt"><?php /* @escapeNotVerified */ echo __('Order #') . $block->getRealOrderId() ?></p><?php endif ?>
	<!-- <?php //if ($error = $block->getErrorMessage()) : ?><p><?php /* @escapeNotVerified */ //echo $error ?></p><?php //endif ?> -->
		<div class="actions-toolbar">
		<div class="primary">
			<a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>">
				<span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span>
			</a>
		</div>
	</div>
</div>
